############# English navigation ##############

# main menu
[[main]]
name = "HOME"
pageRef = "/"
weight = 1



[[main]]
name = "LITERATURE"
pageRef = "/literature"
weight = 2

[[main]]
name = "NEWS"
pageRef = "/news"
weight = 3

[[main]]
name = "VARIETIES"
pageRef = "/varieties"
weight = 3

[[main]]
name = "letments"
pageRef = "/letments"
weight = 3

[[main]]
name = "GENES"
pageRef = "/genes"
weight = 3

[[main]]
weight = 2
name = "RESOURCES"

[[main]]
parent = "RESOURCES"
name = "MZWEBS"
pageRef = "/mzwebs"
weight = 2

[[main]]
parent = "RESOURCES"
name = "LABS"
pageRef = "/labs"
weight = 3

[[main]]
weight = 4
name = "PAGES"

[[main]]
parent = "PAGES"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "PAGES"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "PAGES"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "PAGES"
name = "Categories"
pageRef = "/categories"






