############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1



[[main]]
name = "Literature"
pageRef = "/literature"
weight = 2

[[main]]
name = "News"
pageRef = "/news"
weight = 3



[[main]]
name = "Genes"
pageRef = "/genes"
weight = 3

[[main]]
weight = 4
name = "Resources"

[[main]]
parent = "Resources"
name = "Maizewebs"
pageRef = "/maizewebs"
weight = 2

[[main]]
parent = "Resources"
name = "Labs"
pageRef = "/labs"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"




