############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Resources"
pageRef = "/resources"
weight = 2

[[main]]
name = "Literature"
pageRef = "/literature"
weight = 2

[[main]]
name = "news"
pageRef = "/news"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"




